{
  "openapi": "3.0.1",
  "info": {
    "title": "Microsoft.OpenApi.CSharpAnnotations.DocumentGeneration.Tests.SampleApis",
    "version": "1.0.0"
  },
  "servers": [
    {
      "url": "http://localhost:9000"
    },
    {
      "url": "https://myapi.sample.com"
    }
  ],
  "paths": {
    "/V3/samples/{id}": {
      "put": {
        "tags": [
          "Sample V3"
        ],
        "summary": "Sample put 2",
        "operationId": "putV3SamplesById",
        "parameters": [
          {
            "name": "sampleHeaderParam1",
            "in": "header",
            "description": "Header param 1",
            "schema": {
              "type": "number",
              "format": "float"
            }
          },
          {
            "name": "sampleHeaderParam2",
            "in": "header",
            "description": "Header param 2",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "sampleHeaderParam3",
            "in": "header",
            "description": "Header param 3",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "id",
            "in": "path",
            "description": "",
            "required": true,
            "schema": {
              "$ref": "#/components/schemas/Microsoft.OpenApi.CSharpAnnotations.DocumentGeneration.Tests.Contracts.SampleObject1"
            },
            "examples": {
              "example1": {
                "value": {
                  "samplePropertyBool": true,
                  "samplePropertyStringInt": 100,
                  "samplePropertyString1": "SampleObject SamplePropertyString1",
                  "samplePropertyString2": "SampleObject SamplePropertyString2",
                  "samplePropertyString3": "SampleObject SamplePropertyString3",
                  "samplePropertyString4": "SampleObject SamplePropertyString4",
                  "samplePropertyEnum": 100
                }
              }
            }
          },
          {
            "name": "queryString",
            "in": "query",
            "description": "The sample query string",
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "description": "Request Body Example",
          "content": {
            "application/json": {
              "schema": {
                "anyOf": [
                  {
                    "type": "string",
                    "example": "Request Body Example"
                  },
                  {
                    "$ref": "#/components/schemas/Microsoft.OpenApi.CSharpAnnotations.DocumentGeneration.Tests.Contracts.SampleObject1"
                  }
                ]
              },
              "examples": {
                "example1": {
                  "value": "Request Body Example"
                }
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "Response 200 Example 2",
            "content": {
              "application/json": {
                "schema": {
                  "anyOf": [
                    {
                      "type": "string",
                      "example": "Response 200 Example 1"
                    },
                    {
                      "$ref": "#/components/schemas/Microsoft.OpenApi.CSharpAnnotations.DocumentGeneration.Tests.Contracts.SampleObject4"
                    }
                  ]
                },
                "examples": {
                  "Example one": {
                    "value": "Response 200 Example 1"
                  },
                  "Example two": {
                    "value": "Response 200 Example 2"
                  },
                  "example1": {
                    "value": {
                      "samplePropertyObject": {
                        "samplePropertyEnum": 100,
                        "samplePropertyInt": "SampleObject2 SamplePropertyInt",
                        "samplePropertyObjectDictionary": {
                          "SampleKey1": {
                            "samplePropertyBool": true,
                            "samplePropertyStringInt": 100,
                            "samplePropertyString1": "SampleObject SamplePropertyString1",
                            "samplePropertyString2": "SampleObject SamplePropertyString2",
                            "samplePropertyString3": "SampleObject SamplePropertyString3",
                            "samplePropertyString4": "SampleObject SamplePropertyString4",
                            "samplePropertyEnum": 100
                          }
                        },
                        "samplePropertyObjectList": [
                          {
                            "samplePropertyBool": true,
                            "samplePropertyStringInt": 100,
                            "samplePropertyString1": "SampleObject SamplePropertyString1",
                            "samplePropertyString2": "SampleObject SamplePropertyString2",
                            "samplePropertyString3": "SampleObject SamplePropertyString3",
                            "samplePropertyString4": "SampleObject SamplePropertyString4",
                            "samplePropertyEnum": 100
                          }
                        ],
                        "samplePropertyString1": "SampleObject2 SamplePropertyString1"
                      },
                      "Sample3PropertyObject": {
                        "samplePropertyObject": {
                          "samplePropertyEnum": 100,
                          "samplePropertyInt": "SampleObject2 SamplePropertyInt",
                          "samplePropertyObjectDictionary": {
                            "SampleKey1": {
                              "samplePropertyBool": true,
                              "samplePropertyStringInt": 100,
                              "samplePropertyString1": "SampleObject SamplePropertyString1",
                              "samplePropertyString2": "SampleObject SamplePropertyString2",
                              "samplePropertyString3": "SampleObject SamplePropertyString3",
                              "samplePropertyString4": "SampleObject SamplePropertyString4",
                              "samplePropertyEnum": 100
                            }
                          },
                          "samplePropertyObjectList": [
                            {
                              "samplePropertyBool": true,
                              "samplePropertyStringInt": 100,
                              "samplePropertyString1": "SampleObject SamplePropertyString1",
                              "samplePropertyString2": "SampleObject SamplePropertyString2",
                              "samplePropertyString3": "SampleObject SamplePropertyString3",
                              "samplePropertyString4": "SampleObject SamplePropertyString4",
                              "samplePropertyEnum": 100
                            }
                          ],
                          "samplePropertyString1": "SampleObject2 SamplePropertyString1"
                        },
                        "samplePropertyObjectList": [
                          {
                            "samplePropertyBool": true,
                            "samplePropertyStringInt": 100,
                            "samplePropertyString1": "SampleObject SamplePropertyString1",
                            "samplePropertyString2": "SampleObject SamplePropertyString2",
                            "samplePropertyString3": "SampleObject SamplePropertyString3",
                            "samplePropertyString4": "SampleObject SamplePropertyString4",
                            "samplePropertyEnum": 100
                          }
                        ]
                      },
                      "SamplePropertyObjectList": [
                        {
                          "samplePropertyBool": true,
                          "samplePropertyStringInt": 100,
                          "samplePropertyString1": "SampleObject SamplePropertyString1",
                          "samplePropertyString2": "SampleObject SamplePropertyString2",
                          "samplePropertyString3": "SampleObject SamplePropertyString3",
                          "samplePropertyString4": "SampleObject SamplePropertyString4",
                          "samplePropertyEnum": 100
                        }
                      ]
                    }
                  },
                  "example2": {
                    "value": {
                      "samplePropertyObject": {
                        "samplePropertyEnum": 100,
                        "samplePropertyInt": "SampleObject2 SamplePropertyInt",
                        "samplePropertyObjectDictionary": {
                          "SampleKey1": {
                            "samplePropertyBool": true,
                            "samplePropertyStringInt": 100,
                            "samplePropertyString1": "SampleObject SamplePropertyString1",
                            "samplePropertyString2": "SampleObject SamplePropertyString2",
                            "samplePropertyString3": "SampleObject SamplePropertyString3",
                            "samplePropertyString4": "SampleObject SamplePropertyString4",
                            "samplePropertyEnum": 100
                          }
                        },
                        "samplePropertyObjectList": [
                          {
                            "samplePropertyBool": true,
                            "samplePropertyStringInt": 100,
                            "samplePropertyString1": "SampleObject SamplePropertyString1",
                            "samplePropertyString2": "SampleObject SamplePropertyString2",
                            "samplePropertyString3": "SampleObject SamplePropertyString3",
                            "samplePropertyString4": "SampleObject SamplePropertyString4",
                            "samplePropertyEnum": 100
                          }
                        ],
                        "samplePropertyString1": "SampleObject2 SamplePropertyString1"
                      },
                      "Sample3PropertyObject": {
                        "samplePropertyObject": {
                          "samplePropertyEnum": 100,
                          "samplePropertyInt": "SampleObject2 SamplePropertyInt",
                          "samplePropertyObjectDictionary": {
                            "SampleKey1": {
                              "samplePropertyBool": true,
                              "samplePropertyStringInt": 100,
                              "samplePropertyString1": "SampleObject SamplePropertyString1",
                              "samplePropertyString2": "SampleObject SamplePropertyString2",
                              "samplePropertyString3": "SampleObject SamplePropertyString3",
                              "samplePropertyString4": "SampleObject SamplePropertyString4",
                              "samplePropertyEnum": 100
                            }
                          },
                          "samplePropertyObjectList": [
                            {
                              "samplePropertyBool": true,
                              "samplePropertyStringInt": 100,
                              "samplePropertyString1": "SampleObject SamplePropertyString1",
                              "samplePropertyString2": "SampleObject SamplePropertyString2",
                              "samplePropertyString3": "SampleObject SamplePropertyString3",
                              "samplePropertyString4": "SampleObject SamplePropertyString4",
                              "samplePropertyEnum": 100
                            }
                          ],
                          "samplePropertyString1": "SampleObject2 SamplePropertyString1"
                        },
                        "samplePropertyObjectList": [
                          {
                            "samplePropertyBool": true,
                            "samplePropertyStringInt": 100,
                            "samplePropertyString1": "SampleObject SamplePropertyString1",
                            "samplePropertyString2": "SampleObject SamplePropertyString2",
                            "samplePropertyString3": "SampleObject SamplePropertyString3",
                            "samplePropertyString4": "SampleObject SamplePropertyString4",
                            "samplePropertyEnum": 100
                          }
                        ]
                      },
                      "SamplePropertyObjectList": [
                        {
                          "samplePropertyBool": true,
                          "samplePropertyStringInt": 100,
                          "samplePropertyString1": "SampleObject SamplePropertyString1",
                          "samplePropertyString2": "SampleObject SamplePropertyString2",
                          "samplePropertyString3": "SampleObject SamplePropertyString3",
                          "samplePropertyString4": "SampleObject SamplePropertyString4",
                          "samplePropertyEnum": 100
                        }
                      ]
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad request",
            "content": {
              "application/json": {
                "schema": {
                  "type": "string"
                }
              }
            }
          }
        }
      }
    },
    "/V4/samples/{id}": {
      "post": {
        "tags": [
          "Sample V4"
        ],
        "summary": "Sample get 1",
        "operationId": "postV4SamplesById",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "id2",
            "required": true,
            "schema": {
              "type": "string",
              "example": "id1"
            },
            "examples": {
              "Example one": {
                "value": "id1"
              },
              "Example two": {
                "value": "id2"
              }
            }
          },
          {
            "name": "queryBool",
            "in": "query",
            "description": "false",
            "required": true,
            "schema": {
              "type": "boolean",
              "example": true
            },
            "examples": {
              "example1": {
                "value": true
              },
              "example2": {
                "value": false
              }
            }
          },
          {
            "name": "sampleHeaderParam1",
            "in": "header",
            "description": "Header param 1",
            "schema": {
              "type": "number",
              "format": "float",
              "example": "Sample header 1"
            },
            "examples": {
              "example1": {
                "value": "Sample header 1"
              }
            }
          },
          {
            "name": "sampleHeaderParam2",
            "in": "header",
            "description": "Header param 2",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "sampleHeaderParam3",
            "in": "header",
            "description": "Header param 3",
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Microsoft.OpenApi.CSharpAnnotations.DocumentGeneration.Tests.Contracts.SampleObject1"
              },
              "examples": {
                "example1": {
                  "value": {
                    "samplePropertyBool": true,
                    "samplePropertyStringInt": 100,
                    "samplePropertyString1": "SampleObject SamplePropertyString1",
                    "samplePropertyString2": "SampleObject SamplePropertyString2",
                    "samplePropertyString3": "SampleObject SamplePropertyString3",
                    "samplePropertyString4": "SampleObject SamplePropertyString4",
                    "samplePropertyEnum": 100
                  }
                }
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "Sample object",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Microsoft.OpenApi.CSharpAnnotations.DocumentGeneration.Tests.Contracts.SampleObject4"
                },
                "examples": {
                  "example1": {
                    "value": {
                      "samplePropertyObject": {
                        "samplePropertyEnum": 100,
                        "samplePropertyInt": "SampleObject2 SamplePropertyInt",
                        "samplePropertyObjectDictionary": {
                          "SampleKey1": {
                            "samplePropertyBool": true,
                            "samplePropertyStringInt": 100,
                            "samplePropertyString1": "SampleObject SamplePropertyString1",
                            "samplePropertyString2": "SampleObject SamplePropertyString2",
                            "samplePropertyString3": "SampleObject SamplePropertyString3",
                            "samplePropertyString4": "SampleObject SamplePropertyString4",
                            "samplePropertyEnum": 100
                          }
                        },
                        "samplePropertyObjectList": [
                          {
                            "samplePropertyBool": true,
                            "samplePropertyStringInt": 100,
                            "samplePropertyString1": "SampleObject SamplePropertyString1",
                            "samplePropertyString2": "SampleObject SamplePropertyString2",
                            "samplePropertyString3": "SampleObject SamplePropertyString3",
                            "samplePropertyString4": "SampleObject SamplePropertyString4",
                            "samplePropertyEnum": 100
                          }
                        ],
                        "samplePropertyString1": "SampleObject2 SamplePropertyString1"
                      },
                      "Sample3PropertyObject": {
                        "samplePropertyObject": {
                          "samplePropertyEnum": 100,
                          "samplePropertyInt": "SampleObject2 SamplePropertyInt",
                          "samplePropertyObjectDictionary": {
                            "SampleKey1": {
                              "samplePropertyBool": true,
                              "samplePropertyStringInt": 100,
                              "samplePropertyString1": "SampleObject SamplePropertyString1",
                              "samplePropertyString2": "SampleObject SamplePropertyString2",
                              "samplePropertyString3": "SampleObject SamplePropertyString3",
                              "samplePropertyString4": "SampleObject SamplePropertyString4",
                              "samplePropertyEnum": 100
                            }
                          },
                          "samplePropertyObjectList": [
                            {
                              "samplePropertyBool": true,
                              "samplePropertyStringInt": 100,
                              "samplePropertyString1": "SampleObject SamplePropertyString1",
                              "samplePropertyString2": "SampleObject SamplePropertyString2",
                              "samplePropertyString3": "SampleObject SamplePropertyString3",
                              "samplePropertyString4": "SampleObject SamplePropertyString4",
                              "samplePropertyEnum": 100
                            }
                          ],
                          "samplePropertyString1": "SampleObject2 SamplePropertyString1"
                        },
                        "samplePropertyObjectList": [
                          {
                            "samplePropertyBool": true,
                            "samplePropertyStringInt": 100,
                            "samplePropertyString1": "SampleObject SamplePropertyString1",
                            "samplePropertyString2": "SampleObject SamplePropertyString2",
                            "samplePropertyString3": "SampleObject SamplePropertyString3",
                            "samplePropertyString4": "SampleObject SamplePropertyString4",
                            "samplePropertyEnum": 100
                          }
                        ]
                      },
                      "SamplePropertyObjectList": [
                        {
                          "samplePropertyBool": true,
                          "samplePropertyStringInt": 100,
                          "samplePropertyString1": "SampleObject SamplePropertyString1",
                          "samplePropertyString2": "SampleObject SamplePropertyString2",
                          "samplePropertyString3": "SampleObject SamplePropertyString3",
                          "samplePropertyString4": "SampleObject SamplePropertyString4",
                          "samplePropertyEnum": 100
                        }
                      ]
                    }
                  },
                  "example2": {
                    "value": {
                      "samplePropertyObject": {
                        "samplePropertyEnum": 100,
                        "samplePropertyInt": "SampleObject2 SamplePropertyInt",
                        "samplePropertyObjectDictionary": {
                          "SampleKey1": {
                            "samplePropertyBool": true,
                            "samplePropertyStringInt": 100,
                            "samplePropertyString1": "SampleObject SamplePropertyString1",
                            "samplePropertyString2": "SampleObject SamplePropertyString2",
                            "samplePropertyString3": "SampleObject SamplePropertyString3",
                            "samplePropertyString4": "SampleObject SamplePropertyString4",
                            "samplePropertyEnum": 100
                          }
                        },
                        "samplePropertyObjectList": [
                          {
                            "samplePropertyBool": true,
                            "samplePropertyStringInt": 100,
                            "samplePropertyString1": "SampleObject SamplePropertyString1",
                            "samplePropertyString2": "SampleObject SamplePropertyString2",
                            "samplePropertyString3": "SampleObject SamplePropertyString3",
                            "samplePropertyString4": "SampleObject SamplePropertyString4",
                            "samplePropertyEnum": 100
                          }
                        ],
                        "samplePropertyString1": "SampleObject2 SamplePropertyString1"
                      },
                      "Sample3PropertyObject": {
                        "samplePropertyObject": {
                          "samplePropertyEnum": 100,
                          "samplePropertyInt": "SampleObject2 SamplePropertyInt",
                          "samplePropertyObjectDictionary": {
                            "SampleKey1": {
                              "samplePropertyBool": true,
                              "samplePropertyStringInt": 100,
                              "samplePropertyString1": "SampleObject SamplePropertyString1",
                              "samplePropertyString2": "SampleObject SamplePropertyString2",
                              "samplePropertyString3": "SampleObject SamplePropertyString3",
                              "samplePropertyString4": "SampleObject SamplePropertyString4",
                              "samplePropertyEnum": 100
                            }
                          },
                          "samplePropertyObjectList": [
                            {
                              "samplePropertyBool": true,
                              "samplePropertyStringInt": 100,
                              "samplePropertyString1": "SampleObject SamplePropertyString1",
                              "samplePropertyString2": "SampleObject SamplePropertyString2",
                              "samplePropertyString3": "SampleObject SamplePropertyString3",
                              "samplePropertyString4": "SampleObject SamplePropertyString4",
                              "samplePropertyEnum": 100
                            }
                          ],
                          "samplePropertyString1": "SampleObject2 SamplePropertyString1"
                        },
                        "samplePropertyObjectList": [
                          {
                            "samplePropertyBool": true,
                            "samplePropertyStringInt": 100,
                            "samplePropertyString1": "SampleObject SamplePropertyString1",
                            "samplePropertyString2": "SampleObject SamplePropertyString2",
                            "samplePropertyString3": "SampleObject SamplePropertyString3",
                            "samplePropertyString4": "SampleObject SamplePropertyString4",
                            "samplePropertyEnum": 100
                          }
                        ]
                      },
                      "SamplePropertyObjectList": [
                        {
                          "samplePropertyBool": true,
                          "samplePropertyStringInt": 100,
                          "samplePropertyString1": "SampleObject SamplePropertyString1",
                          "samplePropertyString2": "SampleObject SamplePropertyString2",
                          "samplePropertyString3": "SampleObject SamplePropertyString3",
                          "samplePropertyString4": "SampleObject SamplePropertyString4",
                          "samplePropertyEnum": 100
                        }
                      ]
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad request",
            "content": {
              "application/json": {
                "schema": {
                  "type": "string"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "Microsoft.OpenApi.CSharpAnnotations.DocumentGeneration.Tests.Contracts.SampleObject1": {
        "required": [
          "samplePropertyString3",
          "samplePropertyString4",
          "samplePropertyEnum"
        ],
        "type": "object",
        "properties": {
          "samplePropertyBool": {
            "type": "boolean",
            "description": "Gets or sets the sample property bool"
          },
          "samplePropertyStringInt": {
            "type": "integer",
            "description": "Gets or sets the sample property int",
            "format": "int32"
          },
          "samplePropertyString1": {
            "type": "string",
            "description": "Gets or sets the sample property string 1"
          },
          "samplePropertyString2": {
            "type": "string",
            "description": "Gets or sets the sample property string 2"
          },
          "samplePropertyString3": {
            "type": "string",
            "description": "Gets or sets the sample property string 3"
          },
          "samplePropertyString4": {
            "type": "string",
            "description": "Gets or sets the sample property string 4"
          },
          "samplePropertyEnum": {
            "enum": [
              "SampleEnumValue1",
              "SampleEnumValue2"
            ],
            "type": "string",
            "description": "Gets or sets the sample property enum"
          }
        },
        "example": {
          "samplePropertyBool": true,
          "samplePropertyStringInt": 100,
          "samplePropertyString1": "SampleObject SamplePropertyString1",
          "samplePropertyString2": "SampleObject SamplePropertyString2",
          "samplePropertyString3": "SampleObject SamplePropertyString3",
          "samplePropertyString4": "SampleObject SamplePropertyString4",
          "samplePropertyEnum": 100
        }
      },
      "Microsoft.OpenApi.CSharpAnnotations.DocumentGeneration.Tests.Contracts.SampleObject4": {
        "required": [
          "samplePropertyObject",
          "SamplePropertyObjectList"
        ],
        "type": "object",
        "properties": {
          "samplePropertyObject": {
            "$ref": "#/components/schemas/Microsoft.OpenApi.CSharpAnnotations.DocumentGeneration.Tests.Contracts.SampleObject2"
          },
          "Sample3PropertyObject": {
            "$ref": "#/components/schemas/Microsoft.OpenApi.CSharpAnnotations.DocumentGeneration.Tests.Contracts.SampleObject3"
          },
          "SamplePropertyObjectList": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/Microsoft.OpenApi.CSharpAnnotations.DocumentGeneration.Tests.Contracts.SampleObject1"
            },
            "description": "Gets the sample property object list"
          }
        },
        "example": {
          "samplePropertyObject": {
            "samplePropertyEnum": 100,
            "samplePropertyInt": "SampleObject2 SamplePropertyInt",
            "samplePropertyObjectDictionary": {
              "SampleKey1": {
                "samplePropertyBool": true,
                "samplePropertyStringInt": 100,
                "samplePropertyString1": "SampleObject SamplePropertyString1",
                "samplePropertyString2": "SampleObject SamplePropertyString2",
                "samplePropertyString3": "SampleObject SamplePropertyString3",
                "samplePropertyString4": "SampleObject SamplePropertyString4",
                "samplePropertyEnum": 100
              }
            },
            "samplePropertyObjectList": [
              {
                "samplePropertyBool": true,
                "samplePropertyStringInt": 100,
                "samplePropertyString1": "SampleObject SamplePropertyString1",
                "samplePropertyString2": "SampleObject SamplePropertyString2",
                "samplePropertyString3": "SampleObject SamplePropertyString3",
                "samplePropertyString4": "SampleObject SamplePropertyString4",
                "samplePropertyEnum": 100
              }
            ],
            "samplePropertyString1": "SampleObject2 SamplePropertyString1"
          },
          "Sample3PropertyObject": {
            "samplePropertyObject": {
              "samplePropertyEnum": 100,
              "samplePropertyInt": "SampleObject2 SamplePropertyInt",
              "samplePropertyObjectDictionary": {
                "SampleKey1": {
                  "samplePropertyBool": true,
                  "samplePropertyStringInt": 100,
                  "samplePropertyString1": "SampleObject SamplePropertyString1",
                  "samplePropertyString2": "SampleObject SamplePropertyString2",
                  "samplePropertyString3": "SampleObject SamplePropertyString3",
                  "samplePropertyString4": "SampleObject SamplePropertyString4",
                  "samplePropertyEnum": 100
                }
              },
              "samplePropertyObjectList": [
                {
                  "samplePropertyBool": true,
                  "samplePropertyStringInt": 100,
                  "samplePropertyString1": "SampleObject SamplePropertyString1",
                  "samplePropertyString2": "SampleObject SamplePropertyString2",
                  "samplePropertyString3": "SampleObject SamplePropertyString3",
                  "samplePropertyString4": "SampleObject SamplePropertyString4",
                  "samplePropertyEnum": 100
                }
              ],
              "samplePropertyString1": "SampleObject2 SamplePropertyString1"
            },
            "samplePropertyObjectList": [
              {
                "samplePropertyBool": true,
                "samplePropertyStringInt": 100,
                "samplePropertyString1": "SampleObject SamplePropertyString1",
                "samplePropertyString2": "SampleObject SamplePropertyString2",
                "samplePropertyString3": "SampleObject SamplePropertyString3",
                "samplePropertyString4": "SampleObject SamplePropertyString4",
                "samplePropertyEnum": 100
              }
            ]
          },
          "SamplePropertyObjectList": [
            {
              "samplePropertyBool": true,
              "samplePropertyStringInt": 100,
              "samplePropertyString1": "SampleObject SamplePropertyString1",
              "samplePropertyString2": "SampleObject SamplePropertyString2",
              "samplePropertyString3": "SampleObject SamplePropertyString3",
              "samplePropertyString4": "SampleObject SamplePropertyString4",
              "samplePropertyEnum": 100
            }
          ]
        }
      },
      "Microsoft.OpenApi.CSharpAnnotations.DocumentGeneration.Tests.Contracts.SampleObject2": {
        "required": [
          "samplePropertyInt",
          "samplePropertyObjectDictionary",
          "samplePropertyObjectList"
        ],
        "type": "object",
        "properties": {
          "samplePropertyEnum": {
            "enum": [
              "SampleEnumValue1",
              "SampleEnumValue2"
            ],
            "type": "string",
            "description": "Gets or sets the sample property enum"
          },
          "samplePropertyInt": {
            "type": "string",
            "description": "Gets or sets the sample property string 1"
          },
          "samplePropertyObjectDictionary": {
            "type": "object",
            "additionalProperties": {
              "$ref": "#/components/schemas/Microsoft.OpenApi.CSharpAnnotations.DocumentGeneration.Tests.Contracts.SampleObject1"
            },
            "description": "Gets the sample property object dictionary"
          },
          "samplePropertyObjectList": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/Microsoft.OpenApi.CSharpAnnotations.DocumentGeneration.Tests.Contracts.SampleObject1"
            },
            "description": "Gets the sample property object list"
          },
          "samplePropertyString1": {
            "type": "string",
            "description": "Gets or sets the sample property string 1"
          }
        }
      },
      "Microsoft.OpenApi.CSharpAnnotations.DocumentGeneration.Tests.Contracts.SampleObject3": {
        "required": [
          "samplePropertyObject"
        ],
        "type": "object",
        "properties": {
          "samplePropertyObject": {
            "$ref": "#/components/schemas/Microsoft.OpenApi.CSharpAnnotations.DocumentGeneration.Tests.Contracts.SampleObject2"
          },
          "samplePropertyObjectList": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/Microsoft.OpenApi.CSharpAnnotations.DocumentGeneration.Tests.Contracts.SampleObject1"
            },
            "description": "Gets the sample property object list"
          }
        }
      }
    }
  }
}